### ISSUE TITLE
Generate a QRDA1 from CCDA file?

### ISSUE THREAD

**Issue by mikecarroll** [MeasureAuthoringTool/health-data-standards#133]
Looking for guidance on how to use this project to convert generate/export a QRDA1 from a CCDA. It seems like it's possible from the README, but I couldn't find any documentation on how to do so.

**Comment by eedrummer** [comment]
@mikecarroll This really isn't an issue. A question like this would be best directed at the popHealth mailing list: pophealth-dev@googlegroups.com

With some work, this is possible, but I don't think you can do this out of the box.

You can import a CCDA using the HealthDataStandards::Import::CCDA::PatientImporter class. See this test for an example:

https://github.com/projectcypress/health-data-standards/blob/master/test/unit/import/ccda/patient_importer_test.rb#L12

That will give you a Record object that will have the clinical data extracted from the CCDA document. The next step would be to export the Record object to a QRDA Cat I. That can be done with the HealthDataStandards::Export::Cat1 class. See this test for an example:
https://github.com/projectcypress/health-data-standards/blob/master/test/unit/export/cat_1_test.rb#L23

The problem that you will run into is that the QRDA Cat I exporter expects Entry objects stored in the Record to have an OID populated. The CCDA importer does not assign these OIDs (it's not a trivial assignment). So you will likely get an empty data section in the resulting QRDA Cat I document because the QRDA Cat I scoop and filter logic will remove all of the data (no matching OIDs).

Depending on how you want to use the library and the nature of your data coming over in CCDA, you could work with the Record object created from the import to assign the Entry objects the proper OIDs.
