### ISSUE TITLE
C32 documents missing unique <id>

### ISSUE THREAD

**Issue by jmandel** [MeasureAuthoringTool/health-data-standards#14]
The C32 template has the ClinicalDocument's ID hard-coded:
https://github.com/projectcypress/health-data-standards/blob/master/templates/show.c32.erb#L9

```
  <id root="2.16.840.1.113883.3.72" extension="HITSP_C32v2.5_Rev6_16Sections_Entries_MinimalErrors" assigningAuthorityName="NIST Healthcare Project"/>
```

Looks like this line was cut/pasted from a NIST validation example -- but this ID should _uniquely_ identify a CDA document...

**Comment by jletourneau80** [comment]
Thanks - we're on it

**Comment by abgoldstein** [comment]
Thanks for the catch. I'm updating the template to use 2.16.840.1.113883.19.5, the OID we've used to identify Cypress, as the value of root. Since this issue we've also modified the extension attribute to be a unique ID for the given patient, so this should uniquely identify our document.

I'm making this change for both the C32 and CCDA templates. I'll check this into our develop branch and it will be reflected in master with our next release.
